### PR TITLE
Update requirements.txt

### PR DESCRIPTION
**Pull request by cnukaus**
collapse_type is removed from eth_abi 2.0, so need to use eth_abi 1.3.0 

Below is the error running python -m peth
 >
File "C:\ProgramData\Miniconda3\lib\site-packages\web3\utils\abi.py", line 10, in <module>
    from eth_abi.abi import (
ImportError: cannot import name 'collapse_type' from 'eth_abi.abi' (C:\ProgramData\Miniconda3\lib\site-packages\eth_abi\abi.py)

### CODE REVIEW

**Comment by lmy375** [comment]
The error message shows it is `web3`'s requirement issue. `peth` works fine with `eth_abi 2.0`.
But yes, it's time to update the requirements.  https://github.com/lmy375/peth/commit/9360916365a1f92d953fc56fba838fd5ebcd9a0f

Try `pip install peth` to update. BTW `venv` is recommended to avoiding turning your local package lib into a mess.
